### ISSUE TITLE
Allow several routes on same controller

### ISSUE THREAD

**Issue by MoacirSchmidt** [stablekernel/aqueduct#625] opened 2019-01-22 11:49 UTC
Is there any possibility to subroute GET or POST METHOD in SAME Aqueduct controller?

```
class UserController extends ResourceController {

@Operation.get("/login")
Future<Response> loginByUser(@Bind.query('user') String user, @Bind.query('pass') String pass) async {...}

@Operation.get("/byInnerToken")
Future<Response> loginByToken(@Bind.query('token') String token) async {...}

get("userApi/login?user=aaa&pass=bbbb");
get("userApi/byInnerToken?token=ccc");
```

**Comment by joeconwaystk** [comment] 2019-01-23 00:01
This is a duplicate of #324. There aren't any plans to implement this right now because you can just do a switch, which ends up being more readable:

```dart
@Operation.get("action")
Future<Response> login(@Bind.path("action") String action, @Bind.query('token') String token) async {
  switch(action) {
    case "login": return loginByUser(..);
    default: return Response.notFound();
  }
}
```

**Closed by joeconwaystk** 2019-01-23 00:01 UTC
Labels: duplicate

**Comment by MoacirSchmidt** [comment] 2019-04-02 00:32
What about different parameters? I have to put all parameters together? Even if only a subset of them are used in each case? IMHO this is quite confusing and less readable...
```
@Operation.get("action")
Future<Response> login(@Bind.path("action") String action, @Bind.query('user') String user, @Bind.query('pass') String pass, @Bind.query('token') String token) async {
  switch(action) {
...
```

**Comment by joeconwaystk** [comment] 2019-04-02 00:34
You don't have to bind parameters. `final user = request.raw.queryParameters['user']` is equivalent to binding.
