### ISSUE TITLE
Crash in working aqueduct project after upgrade to flutter 1.17.0 (beta)

### ISSUE THREAD

**Issue by bambinoua** [stablekernel/aqueduct#803] opened 2020-04-07 14:19 UTC
The crash is occured in `package:/postgres/src/substituter.dart:83`. As I saw `aqueduct` still depends on old version of `postgres`. Why? Is it possible to make it depends on `postgres: 2.1.0`?

**Comment by joeconwaystk** [comment] 2020-04-07 14:30
The issue is due to a breaking change in Dart 2.8 (in preparation for non-nullable types) that hasn't been reflected yet in this package. I'm not sure if this issue is fixed in postgres@2.1.0, but you can add a dependency_override to your project's pubspec.yaml to try it out.

**Comment by bambinoua** [comment] 2020-04-07 15:53
I tried to do this but without success. Could you please to help me?
I do this:
```
dependency_overrides:
  postgres: "2.1.0"
```
but when I opened `pubspec.lock` I saw the version `1.0.2`. What I did wrong?

**Comment by bambinoua** [comment] 2020-04-08 06:03
Why are you depends on `postgres: 1.0.2` if it is enough old?

**Closed** 2020-04-08 15:45 UTC
