### ISSUE TITLE
Building with dart2native doesn't work

### ISSUE THREAD

**Issue by ProgrammingLife** [stablekernel/aqueduct#753] opened 2019-12-16 22:36 UTC
```
$ dart2native bin/main.dart -o main-serv

error: import of dart:mirrors is not supported in the current Dart runtime

Failed to generate native files:
Generating AOT snapshot failed!

```

Is this feature not supported yet?

**Comment by joeconwaystk** [comment] 2019-12-17 18:53
Dupe of #669, correct, not supported yet. See that thread for more details.

**Closed by joeconwaystk** 2019-12-17 18:53 UTC
